### ISSUE TITLE
Not enforcing strict types

### ISSUE THREAD

**Issue by tvlooy** [krakjoe/autostrict#6]
Hi Joe

I'm tried to use the module in a Symfony project and with Symfony's app/console webserver the extension doesn't load `php -dzend_extension=autostrict.so app/console server:run`. With the PHP internal webserver it does load but it doesn't enforce a thing `php -dzend_extension=autostrict.so -S localhost:8000 -t web`. I'm on 7.0.3 at the moment. I checked with `phpinfo()`.

I just switched back to my patch https://github.com/tvlooy/php-src/commits/strict_types_ini for now. I'm investigating how much strict stuff is broken in default install. For now, I wanted to leave this report here.

**Comment by krakjoe** [comment]
Can you provide a proper reproducing case, so I can test ... thanks

**Comment by krakjoe** [comment]
Closing, no feedback.

**Comment by tvlooy** [comment]
yeah, I encountered too many cases where strict types were a problem. Maybe I'll take a look at it again later but for now I lost interest in the issue
