### ISSUE TITLE
Whitelist question

### ISSUE THREAD

**Issue by tommy-muehle** [krakjoe/autostrict#7]
Hi,

thx for sharing this extension! 

I personally ran in problems with some libraries in the "vendor" directory which doesn't support strict mode forcing.

So i would like to ask if it possible to whitelist the "src" directory for strict mode forcing instead of ignore some files?

Best regards,
Tommy

**Comment by krakjoe** [comment]
You can ignore paths based on regex patterns, see README.md

**Comment by tommy-muehle** [comment]
I know the "ignore" option, so see my question above. 
But instead of this:

src -> include
vendor/libA -> include
vendor/libB -> ignored by autostrict.ignore
vendor/libC -> ignored by autostrict.ignore
vendor/libD -> ignored by autostrict.ignore
vendor/libE -> ignored by autostrict.ignore
vendor/libF -> ignored by autostrict.ignore
...

For me it make more sense to do this:
autostrict.whitelist = src,vendor/libA

In case it is possible?
